name: ecommerce_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.1.2
  collection: ^1.17.1
  dio: ^5.1.2
  equatable: ^2.0.5
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_signin_button: ^2.0.0
  flutter_svg: ^2.0.4
  get: ^4.6.5
  get_it: ^7.2.0
  google_sign_in: ^6.0.2
  intl: ^0.18.0
  openapi:
    git:
      url: https://github.com/mvukojicic/ecommerce_flutter_api
      #ref: main
  openapi_generator: ^4.0.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/icons/category_icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
