// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        break;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVok2pWr0TDdgiqR6homHpABdqNpP0K-o',
    appId: '1:156103685351:web:860dfa8d5081290f4a9e42',
    messagingSenderId: '156103685351',
    projectId: 'e-commerce-cd334',
    authDomain: 'e-commerce-cd334.firebaseapp.com',
    storageBucket: 'e-commerce-cd334.appspot.com',
    measurementId: 'G-VL6H5JVGSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCWt3-pSVZTEojAflqVLDPC__ZSKLspQg',
    appId: '1:156103685351:android:e844a1a33fe6c78d4a9e42',
    messagingSenderId: '156103685351',
    projectId: 'e-commerce-cd334',
    storageBucket: 'e-commerce-cd334.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiRcm8J__8y3sYzgqFPg8gF_5cqTxdxUo',
    appId: '1:156103685351:ios:43764ca4655574834a9e42',
    messagingSenderId: '156103685351',
    projectId: 'e-commerce-cd334',
    storageBucket: 'e-commerce-cd334.appspot.com',
    androidClientId:
        '156103685351-7k74j4c6qqtj6ule63d61ak75md87an1.apps.googleusercontent.com',
    iosClientId:
        '156103685351-091e1i59hcq9inmp6rsktc77g9n1of4c.apps.googleusercontent.com',
    iosBundleId: 'com.exmaple.verygoodcore.ecommerce-app',
  );
}
