name: ecommerce_app

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Mica Checkout
        uses: actions/checkout@v3
      - name: Mica Flutter Setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.4"
          channel: "stable"
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
      - name: Mica Install Dependencies
        run: flutter pub get
      - name: Here Mica Check Formatting
        run: dart format --line-length 80 --set-exit-if-changed lib test
      - name: And Here Mica Analyze
        run: flutter analyze ${{inputs.analyze_directories}}
